import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* screen */}
      <div className="h-screen bg-ghost-white dark:bg-rich-black selection:bg-[#1C1E30] selection:text-ghost-white dark:selection:bg-ghost-white-100 dark:selection:text-rich-black">
        {/* divider */}
        <div className="flex flex-col md:flex-row h-full w-full">
          {/* contact container */}
          <div className="flex flex-col h-full w-full md:max-w-lg items-center transition-all">
            {/* header component */}
            <div className="flex flex-col w-full px-4 py-2 justify-center items-end shadow-md">
              <div>
                <div className="flex flex-col bg-ghost-white-100 rounded-full w-[48px] h-[48px] justify-center items-center"></div>
              </div>
            </div>
            {/* search component */}
            <div className="flex flex-col w-full px-6 py-8 md:px-8 gap-4">
              <input
                type="text"
                placeholder="Search"
                className="w-full h-12 px-6 py-1.5 rounded-3xl bg-ghost-white-100 outline-1 text-rich-black outline-rich-black dark:bg-[#1C1E30] dark:outline-ghost-white-100 dark:text-ghost-white transition-all"
              />
            </div>
            {/* option list */}
            <div className="flex flex-col w-full h-8" >
            </div>
            {/* contact list */}
            <div className="flex flex-col w-full items-center md:items-start transition-all">
              {/* contact item */}
              <div className="flex flex-row w-full px-4 pt-3 pb-5 cursor-pointer shadow-sm">
                {/* icon container */}
                <div className="flex flex-col w-auto justify-center items-center mr-6">
                  {/* icon */}
                  <div className="flex flex-col bg-ghost-white-100 rounded-full w-[64px] h-[64px] justify-center items-center">
                    {/* image */}
                  </div>
                </div>
                {/* text container */}
                <div className="flex flex-col w-full overflow-hidden">
                  <div className="flex font-bold text-rich-black">
                    <p>TypeScript</p>
                  </div>
                  <div className="flex flex-col overflow-hidden max-h-6">
                    <p className="text-ghost-white-400 overflow-hidden text-ellipsis">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Sunt quae dolorum est quia inventore cumque minus tempora
                      doloribus quisquam incidunt eveniet nesciunt, culpa
                      officiis provident expedita sapiente doloremque, voluptas
                      iusto.
                    </p>
                  </div>
                </div>
                <div className="flex flex-col w-auto h-auto">
                  <div className="flex flex-col w-full py-1">
                    <p className="text-ghost-white-400 text-sm">12:30</p>
                  </div>
                  <div className="flex flex-col w-auto justify-start items-center">
                    <div className="flex flex-col bg-raspberry rounded-full w-[20px] h-[20px] justify-center items-center">
                      <p className="text-[10px] text-ghost-white">2</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            role="separator"
            className="h-screen md:flex hidden visible border border-ghost-white-900 dark:border-[#1C1E30]"
          ></div>
          {/* chat container */}
          <div className="md:flex md:flex-col hidden w-full items-center justify-center transition-all">
            Second container
          </div>
        </div>
      </div>
    </>
  );
}
